### ISSUE TITLE
Setting to False in config

### ISSUE THREAD

**Issue by B1otto** [aliig/arkserversuite#4]
If I set Announcements to False it still displays. Haven't tried the other ones. Was just trying to disable it because it stays on the screen the whole time while playing.

**Comment by aliig** [comment]
Hey sorry I didn't see this earlier! Im wondering, it's probably the welcome message sending that you don't want to send rather than the periodic announcements. 

I notice the welcome messages and announcements etc are permanent. Classic ark problems.

I'll try to make a way to separate these so both can be disabled.

I'm currently pretty deep into redoing the project with a GUI

**Comment by aliig** [comment]
resolved on a recent commit
